# Generated by Django 6.0.6 on 2026-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('campaign_name', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(choices=[('seo', 'SEO'), ('social_media', 'Social Media'), ('paid_ads', 'Paid Ads'), ('email', 'Email'), ('event', 'Event'), ('content', 'Content'), ('referral', 'Referral')], default='paid_ads', max_length=30)),
                ('source_channel', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_ads', 'Google Ads'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('website', 'Website'), ('youtube', 'YouTube'), ('event_booth', 'Event Booth'), ('referral', 'Referral')], default='facebook', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost'), ('not_interested', 'Not Interested')], default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('interest_level', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='warm', max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
