# Generated by Django 6.0.6 on 2026-06-17 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('campaign_name', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(choices=[('seo', 'SEO'), ('social_media', 'Social Media'), ('paid_ads', 'Paid Ads'), ('email', 'Email'), ('content', 'Content'), ('event', 'Event'), ('brand_awareness', 'Brand Awareness'), ('lead_generation', 'Lead Generation')], default='paid_ads', max_length=30)),
                ('channel', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_ads', 'Google Ads'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('website', 'Website'), ('youtube', 'YouTube'), ('offline_event', 'Offline Event')], default='facebook', max_length=30)),
                ('responsibility', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(default='Marketing Team Lead', max_length=120)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work', to='leads.teamlead'),
        ),
    ]
