# Generated by Django 6.0.6 on 2026-06-17 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_create_demo_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('annual_revenue', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('website', 'Website'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('event', 'Event'), ('referral', 'Referral'), ('paid_ads', 'Paid Ads')], default='website', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('email_engagement', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('social_engagement', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('website_visits', models.PositiveSmallIntegerField(default=0)),
                ('form_submissions', models.PositiveSmallIntegerField(default=0)),
                ('lead_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('lead_grade', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', editable=False, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_leads', to='leads.teamlead')),
            ],
            options={
                'ordering': ['-lead_score', '-updated_at'],
            },
        ),
    ]
