# Generated by Django 6.0.6 on 2026-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('form', 'Form'), ('website', 'Website'), ('chat', 'Chat'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('event', 'Event'), ('referral', 'Referral'), ('paid_ads', 'Paid Ads')], default='website', max_length=30),
        ),
    ]
